# Generated by Django 2.2.6 on 2019-10-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
