# Generated by Django 2.2.6 on 2019-10-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20191024_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
