# Generated by Django 2.2.6 on 2019-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20191027_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_vote',
            field=models.IntegerField(default=0),
        ),
    ]
