# Generated by Django 2.2.6 on 2019-11-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191102_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='count',
        ),
    ]
